repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: task format
        language: system
        types: [python]
      - id: lint2
        name: lint2
        entry: task lint
        language: system
        types: [python]
