repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: task format
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: task lint
        language: system
        types: [python]
